// This file is generated from content/projects.csv. Do not edit it directly.

export const projectRows = [
  {
    "order": 1,
    "slug": "afterglow",
    "templateSlug": "afterglow",
    "titleZh": "百龄坛",
    "titleEn": "Ballantine_30s",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "0:31",
    "previewVideo": "/media/projects/Ballantine_30s.mp4",
    "fullVideo": "/media/projects/Ballantine_30s.mp4",
    "cover": "/media/projects/photo/Ballantine_30s.png",
    "visual": "",
    "featured": true,
    "enabled": true
  },
  {
    "order": 2,
    "slug": "neon-pulse",
    "templateSlug": "neon-pulse",
    "titleZh": "BMW",
    "titleEn": "BMW",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2026",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "4:14",
    "previewVideo": "/media/projects/BMW .mp4",
    "fullVideo": "/media/projects/BMW .mp4",
    "cover": "/media/projects/photo/BMW .png",
    "visual": "",
    "featured": true,
    "enabled": true
  },
  {
    "order": 3,
    "slug": "quiet-tides",
    "templateSlug": "quiet-tides",
    "titleZh": "播",
    "titleEn": "BO",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "摄影 / 剪辑",
    "roleEn": "Cinematography / Edit",
    "duration": "1:11",
    "previewVideo": "/media/projects/BO.mp4",
    "fullVideo": "/media/projects/BO.mp4",
    "cover": "/media/projects/photo/BO.png",
    "visual": "",
    "featured": true,
    "enabled": true
  },
  {
    "order": 4,
    "slug": "kinetic-type",
    "templateSlug": "kinetic-type",
    "titleZh": "HOW_Bra",
    "titleEn": "HOW_Bra",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "0:37",
    "previewVideo": "/media/projects/HOW_Bra.mp4",
    "fullVideo": "/media/projects/HOW_Bra.mp4",
    "cover": "/media/projects/photo/HOW_Bra.png",
    "visual": "",
    "featured": true,
    "enabled": true
  },
  {
    "order": 5,
    "slug": "orbital-form",
    "templateSlug": "orbital-form",
    "titleZh": "华为荣耀",
    "titleEn": "HR Designer",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:56",
    "previewVideo": "/media/projects/HR Designer .mp4",
    "fullVideo": "/media/projects/HR Designer .mp4",
    "cover": "/media/projects/photo/HR Designer .png",
    "visual": "",
    "featured": true,
    "enabled": true
  },
  {
    "order": 6,
    "slug": "nocturne",
    "templateSlug": "nocturne",
    "titleZh": "华为 Y9",
    "titleEn": "HUAWEI Y9",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2024",
    "roleZh": "导演 / 视觉",
    "roleEn": "Direction / Visuals",
    "duration": "1:00",
    "previewVideo": "/media/projects/HUAWEI Y9 .mp4",
    "fullVideo": "/media/projects/HUAWEI Y9 .mp4",
    "cover": "/media/projects/photo/HUAWEI Y9 .png",
    "visual": "",
    "featured": true,
    "enabled": true
  },
  {
    "order": 7,
    "slug": "morning-haze",
    "templateSlug": "afterglow",
    "titleZh": "LOL片头",
    "titleEn": "LOL",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "导演 / 剪辑",
    "roleEn": "Direction / Edit",
    "duration": "0:12",
    "previewVideo": "/media/projects/LOL片头.mp4",
    "fullVideo": "/media/projects/LOL片头.mp4",
    "cover": "/media/projects/photo/LOL片头.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 8,
    "slug": "echo-cuts",
    "templateSlug": "neon-pulse",
    "titleZh": "力士",
    "titleEn": "LUX",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2025",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "1:31",
    "previewVideo": "/media/projects/LUX_.mp4",
    "fullVideo": "/media/projects/LUX_.mp4",
    "cover": "/media/projects/photo/LUX_.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 9,
    "slug": "glimmer-sequence",
    "templateSlug": "kinetic-type",
    "titleZh": "飞利浦",
    "titleEn": "PHILPS",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "5:30",
    "previewVideo": "/media/projects/PHILIPS_.mp4",
    "fullVideo": "/media/projects/PHILIPS_.mp4",
    "cover": "/media/projects/photo/PHILIPS_.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 10,
    "slug": "gravity-study",
    "templateSlug": "orbital-form",
    "titleZh": "QQ全世界圈着玩-穿越AR赛场",
    "titleEn": "QQ",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:15",
    "previewVideo": "/media/projects/QQ全世界圈着玩-穿越AR赛场.mp4",
    "fullVideo": "/media/projects/QQ全世界圈着玩-穿越AR赛场.mp4",
    "cover": "/media/projects/photo/QQ全世界圈着玩-穿越AR赛场.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 11,
    "slug": "city-breath",
    "templateSlug": "quiet-tides",
    "titleZh": "立顿红茶",
    "titleEn": "TWININGS",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2025",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "0:15",
    "previewVideo": "/media/projects/TWININGS.mp4",
    "fullVideo": "/media/projects/TWININGS.mp4",
    "cover": "/media/projects/photo/TWININGS.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 12,
    "slug": "liquid-type",
    "templateSlug": "kinetic-type",
    "titleZh": "VSL",
    "titleEn": "VSL",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "0:34",
    "previewVideo": "/media/projects/VSL.mp4",
    "fullVideo": "/media/projects/VSL.mp4",
    "cover": "/media/projects/photo/VSL.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 13,
    "slug": "spectrum-memory",
    "templateSlug": "orbital-form",
    "titleZh": "奔驰",
    "titleEn": "Smart",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:23",
    "previewVideo": "/media/projects/奔驰_Smart.mp4",
    "fullVideo": "/media/projects/奔驰_Smart.mp4",
    "cover": "/media/projects/photo/奔驰_Smart.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 14,
    "slug": "outline-of-wind",
    "templateSlug": "quiet-tides",
    "titleZh": "大众CC",
    "titleEn": "CC",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:42",
    "previewVideo": "/media/projects/大众_CC.mp4",
    "fullVideo": "/media/projects/大众_CC.mp4",
    "cover": "/media/projects/photo/大众_CC.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 15,
    "slug": "pixel-tides",
    "templateSlug": "kinetic-type",
    "titleZh": "冈本_神诞树",
    "titleEn": "OKAMOTO",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "1:55",
    "previewVideo": "/media/projects/冈本_圣诞树.mp4",
    "fullVideo": "/media/projects/冈本_圣诞树.mp4",
    "cover": "/media/projects/photo/冈本_圣诞树.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 16,
    "slug": "night-signal",
    "templateSlug": "nocturne",
    "titleZh": "杰士邦",
    "titleEn": "JSB",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "0:30",
    "previewVideo": "/media/projects/杰士邦_30s.mp4",
    "fullVideo": "/media/projects/杰士邦_30s.mp4",
    "cover": "/media/projects/photo/杰士邦_30s.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 17,
    "slug": "loop-garden",
    "templateSlug": "orbital-form",
    "titleZh": "仁孚",
    "titleEn": "Zung FU",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "1:02",
    "previewVideo": "/media/projects/仁孚_MG.mp4",
    "fullVideo": "/media/projects/仁孚_MG.mp4",
    "cover": "/media/projects/photo/仁孚_MG.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 18,
    "slug": "silent-ad",
    "templateSlug": "neon-pulse",
    "titleZh": "小电视形象展示",
    "titleEn": "TV",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2024",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "1:07",
    "previewVideo": "/media/projects/小电视形象展示.mp4",
    "fullVideo": "/media/projects/小电视形象展示.mp4",
    "cover": "/media/projects/photo/小电视形象展示.png",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 19,
    "slug": "material-study",
    "templateSlug": "orbital-form",
    "titleZh": "材质实验",
    "titleEn": "Material Study",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "00:34",
    "previewVideo": "https://videos.pexels.com/video-files/853800/853800-hd_1920_1080_30fps.mp4",
    "fullVideo": "https://videos.pexels.com/video-files/853800/853800-hd_1920_1080_30fps.mp4",
    "cover": "/hero-posts/liker-post-04.webp",
    "visual": "",
    "featured": false,
    "enabled": true
  },
  {
    "order": 20,
    "slug": "last-frame",
    "templateSlug": "neon-pulse",
    "titleZh": "最后一帧",
    "titleEn": "Last Frame",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2026",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "00:45",
    "previewVideo": "https://videos.pexels.com/video-files/3130284/3130284-hd_3840_2160_30fps.mp4",
    "fullVideo": "https://videos.pexels.com/video-files/3130284/3130284-hd_3840_2160_30fps.mp4",
    "cover": "/og.png",
    "visual": "",
    "featured": false,
    "enabled": true
  }
] as const;
