// This file is generated from content/projects.csv. Do not edit it directly.

export const projectRows = [
  {
    "order": 1,
    "slug": "afterglow",
    "templateSlug": "afterglow",
    "titleZh": "百龄坛",
    "titleEn": "Ballantine_30s",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "0:31",
    "previewVideo": "/media/projects/afterglow-preview.mp4",
    "fullVideo": "/media/projects/Ballantine_30s.mp4",
    "cover": "/media/projects/photo/Ballantine_30s.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": true,
    "featuredOrder": 1,
    "enabled": true
  },
  {
    "order": 2,
    "slug": "neon-pulse",
    "templateSlug": "neon-pulse",
    "titleZh": "BMW",
    "titleEn": "BMW",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2026",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "4:14",
    "previewVideo": "/media/projects/neon-pulse-preview.mp4",
    "fullVideo": "/media/projects/BMW .mp4",
    "cover": "/media/projects/photo/BMW .webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 3,
    "slug": "quiet-tides",
    "templateSlug": "quiet-tides",
    "titleZh": "播",
    "titleEn": "BO",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "摄影 / 剪辑",
    "roleEn": "Cinematography / Edit",
    "duration": "1:11",
    "previewVideo": "/media/projects/quiet-tides-preview.mp4",
    "fullVideo": "/media/projects/BO.mp4",
    "cover": "/media/projects/photo/BO.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": true,
    "featuredOrder": 3,
    "enabled": true
  },
  {
    "order": 4,
    "slug": "kinetic-type",
    "templateSlug": "kinetic-type",
    "titleZh": "HOW_Bra",
    "titleEn": "HOW_Bra",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "0:37",
    "previewVideo": "/media/projects/kinetic-type-preview.mp4",
    "fullVideo": "/media/projects/HOW_Bra.mp4",
    "cover": "/media/projects/photo/HOW_Bra.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": true,
    "featuredOrder": 6,
    "enabled": true
  },
  {
    "order": 5,
    "slug": "orbital-form",
    "templateSlug": "orbital-form",
    "titleZh": "华为荣耀",
    "titleEn": "HR Designer",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:56",
    "previewVideo": "/media/projects/orbital-form-preview.mp4",
    "fullVideo": "/media/projects/HR Designer .mp4",
    "cover": "/media/projects/photo/HR Designer .webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": true,
    "featuredOrder": 5,
    "enabled": true
  },
  {
    "order": 6,
    "slug": "nocturne",
    "templateSlug": "nocturne",
    "titleZh": "华为 Y9",
    "titleEn": "HUAWEI Y9",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2024",
    "roleZh": "导演 / 视觉",
    "roleEn": "Direction / Visuals",
    "duration": "1:00",
    "previewVideo": "/media/projects/nocturne-preview.mp4",
    "fullVideo": "/media/projects/HUAWEI Y9 .mp4",
    "cover": "/media/projects/photo/HUAWEI Y9 .webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 7,
    "slug": "morning-haze",
    "templateSlug": "afterglow",
    "titleZh": "LOL片头",
    "titleEn": "LOL",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2025",
    "roleZh": "导演 / 剪辑",
    "roleEn": "Direction / Edit",
    "duration": "0:12",
    "previewVideo": "/media/projects/morning-haze-preview.mp4",
    "fullVideo": "/media/projects/LOL片头.mp4",
    "cover": "/media/projects/photo/LOL片头.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 8,
    "slug": "echo-cuts",
    "templateSlug": "neon-pulse",
    "titleZh": "力士",
    "titleEn": "LUX",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2025",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "1:31",
    "previewVideo": "/media/projects/echo-cuts-preview.mp4",
    "fullVideo": "/media/projects/LUX_.mp4",
    "cover": "/media/projects/photo/LUX_.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 9,
    "slug": "glimmer-sequence",
    "templateSlug": "kinetic-type",
    "titleZh": "飞利浦",
    "titleEn": "PHILPS",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "5:30",
    "previewVideo": "/media/projects/glimmer-sequence-preview.mp4",
    "fullVideo": "/media/projects/PHILIPS_.mp4",
    "cover": "/media/projects/photo/PHILIPS_.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 10,
    "slug": "gravity-study",
    "templateSlug": "orbital-form",
    "titleZh": "QQ全世界圈着玩-穿越AR赛场",
    "titleEn": "QQ",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:15",
    "previewVideo": "/media/projects/gravity-study-preview.mp4",
    "fullVideo": "/media/projects/QQ全世界圈着玩-穿越AR赛场.mp4",
    "cover": "/media/projects/photo/QQ全世界圈着玩-穿越AR赛场.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 11,
    "slug": "city-breath",
    "templateSlug": "quiet-tides",
    "titleZh": "立顿红茶",
    "titleEn": "TWININGS",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2025",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "0:15",
    "previewVideo": "/media/projects/city-breath-preview.mp4",
    "fullVideo": "/media/projects/TWININGS.mp4",
    "cover": "/media/projects/photo/TWININGS.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 12,
    "slug": "liquid-type",
    "templateSlug": "kinetic-type",
    "titleZh": "VSL",
    "titleEn": "VSL",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "0:34",
    "previewVideo": "/media/projects/liquid-type-preview.mp4",
    "fullVideo": "/media/projects/VSL.mp4",
    "cover": "/media/projects/photo/VSL.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 13,
    "slug": "spectrum-memory",
    "templateSlug": "orbital-form",
    "titleZh": "奔驰",
    "titleEn": "Smart",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:23",
    "previewVideo": "/media/projects/spectrum-memory-preview.mp4",
    "fullVideo": "/media/projects/奔驰_Smart.mp4",
    "cover": "/media/projects/photo/奔驰_Smart.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 14,
    "slug": "outline-of-wind",
    "templateSlug": "quiet-tides",
    "titleZh": "大众CC",
    "titleEn": "CC",
    "categoryZh": "三维动画",
    "categoryEn": "3D Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "1:42",
    "previewVideo": "/media/projects/outline-of-wind-preview.mp4",
    "fullVideo": "/media/projects/大众_CC.mp4",
    "cover": "/media/projects/photo/大众_CC.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 15,
    "slug": "pixel-tides",
    "templateSlug": "kinetic-type",
    "titleZh": "冈本_神诞树",
    "titleEn": "OKAMOTO",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "1:55",
    "previewVideo": "/media/projects/pixel-tides-preview.mp4",
    "fullVideo": "/media/projects/冈本_圣诞树.mp4",
    "cover": "/media/projects/photo/冈本_圣诞树.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 16,
    "slug": "night-signal",
    "templateSlug": "nocturne",
    "titleZh": "杰士邦",
    "titleEn": "JSB",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "0:30",
    "previewVideo": "/media/projects/night-signal-preview.mp4",
    "fullVideo": "/media/projects/杰士邦_30s.mp4",
    "cover": "/media/projects/photo/杰士邦_30s.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 17,
    "slug": "loop-garden",
    "templateSlug": "orbital-form",
    "titleZh": "仁孚",
    "titleEn": "Zung FU",
    "categoryZh": "动态设计",
    "categoryEn": "Motion Design",
    "year": "2025",
    "roleZh": "设计 / 动效",
    "roleEn": "Design / Animation",
    "duration": "1:02",
    "previewVideo": "/media/projects/loop-garden-preview.mp4",
    "fullVideo": "/media/projects/仁孚_MG.mp4",
    "cover": "/media/projects/photo/仁孚_MG.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 18,
    "slug": "silent-ad",
    "templateSlug": "neon-pulse",
    "titleZh": "小电视形象展示",
    "titleEn": "TV",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2024",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "1:07",
    "previewVideo": "/media/projects/silent-ad-preview.mp4",
    "fullVideo": "/media/projects/小电视形象展示.mp4",
    "cover": "/media/projects/photo/小电视形象展示.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": true,
    "featuredOrder": 2,
    "enabled": true
  },
  {
    "order": 19,
    "slug": "1",
    "templateSlug": "orbital-form",
    "titleZh": "喜马拉雅AI 波波球",
    "titleEn": "Himalaya AI Bobo Ball",
    "categoryZh": "AI动画",
    "categoryEn": "AI Animation",
    "year": "2025",
    "roleZh": "三维 / 合成",
    "roleEn": "3D / Compositing",
    "duration": "0:52",
    "previewVideo": "/media/projects/1-preview.mp4",
    "fullVideo": "/media/projects/1-full.mp4",
    "cover": "/media/projects/photo/1.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 20,
    "slug": "last-frame",
    "templateSlug": "neon-pulse",
    "titleZh": "最后一帧",
    "titleEn": "Last Frame",
    "categoryZh": "广告",
    "categoryEn": "Commercial",
    "year": "2026",
    "roleZh": "创意 / 后期",
    "roleEn": "Concept / Post",
    "duration": "1:23",
    "previewVideo": "/media/projects/last-frame-preview.mp4",
    "fullVideo": "/media/projects/last-frame-full.mp4",
    "cover": "/media/projects/photo/last-frame.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 21,
    "slug": "project-2026-08-31-01",
    "templateSlug": "afterglow",
    "titleZh": "旋转飞椅",
    "titleEn": "Spinning Swings",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:07",
    "previewVideo": "/media/projects/project-2026-08-31-01-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-01-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-01.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 22,
    "slug": "8",
    "templateSlug": "afterglow",
    "titleZh": "8月限定便宜",
    "titleEn": "August Specials",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:05",
    "previewVideo": "/media/projects/8-preview.mp4",
    "fullVideo": "/media/projects/8-full.mp4",
    "cover": "/media/projects/photo/8.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 23,
    "slug": "588-2",
    "templateSlug": "afterglow",
    "titleZh": "588海滨乐园_2",
    "titleEn": "588 Seaside Park",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:06",
    "previewVideo": "/media/projects/588-2-preview.mp4",
    "fullVideo": "/media/projects/588-2-full.mp4",
    "cover": "/media/projects/photo/588-2.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 24,
    "slug": "project-2026-08-31-07",
    "templateSlug": "afterglow",
    "titleZh": "冰箱",
    "titleEn": "Refrigerator",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:04",
    "previewVideo": "/media/projects/project-2026-08-31-07-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-07-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-07.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 25,
    "slug": "project-2026-08-31-09",
    "templateSlug": "afterglow",
    "titleZh": "德国城堡",
    "titleEn": "German Castles",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:06",
    "previewVideo": "/media/projects/project-2026-08-31-09-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-09-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-09.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 26,
    "slug": "project-2026-08-31-11",
    "templateSlug": "afterglow",
    "titleZh": "毒苹果",
    "titleEn": "Poisoned Apple",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:03",
    "previewVideo": "/media/projects/project-2026-08-31-11-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-11-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-11.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 27,
    "slug": "2",
    "templateSlug": "afterglow",
    "titleZh": "海盗船",
    "titleEn": "Pirate Ship",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:06",
    "previewVideo": "/media/projects/2-preview.mp4",
    "fullVideo": "/media/projects/2-full.mp4",
    "cover": "/media/projects/photo/2.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 28,
    "slug": "project-2026-08-31-15",
    "templateSlug": "afterglow",
    "titleZh": "怀表",
    "titleEn": "Pocket Watch",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:03",
    "previewVideo": "/media/projects/project-2026-08-31-15-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-15-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-15.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 29,
    "slug": "project-2026-08-31-17",
    "templateSlug": "afterglow",
    "titleZh": "精灵王座",
    "titleEn": "The Throne of the Elves",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:08",
    "previewVideo": "/media/projects/project-2026-08-31-17-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-17-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-17.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 30,
    "slug": "project-2026-08-31-19",
    "templateSlug": "afterglow",
    "titleZh": "雷峰塔",
    "titleEn": "Leifeng Pagoda",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:05",
    "previewVideo": "/media/projects/project-2026-08-31-19-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-19-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-19.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 31,
    "slug": "3",
    "templateSlug": "afterglow",
    "titleZh": "梦幻缆车",
    "titleEn": "Fantasy Cable Car",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:04",
    "previewVideo": "/media/projects/3-preview.mp4",
    "fullVideo": "/media/projects/3-full.mp4",
    "cover": "/media/projects/photo/3.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 32,
    "slug": "project-2026-08-31-23",
    "templateSlug": "afterglow",
    "titleZh": "魔法坩埚",
    "titleEn": "Magic Crucible",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:06",
    "previewVideo": "/media/projects/project-2026-08-31-23-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-23-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-23.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 33,
    "slug": "project-2026-08-31-25",
    "templateSlug": "afterglow",
    "titleZh": "魔法烛台",
    "titleEn": "Magic Candlestick",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:03",
    "previewVideo": "/media/projects/project-2026-08-31-25-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-25-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-25.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 34,
    "slug": "project-2026-08-31-27",
    "templateSlug": "afterglow",
    "titleZh": "魔法庄园门",
    "titleEn": "The Gate to the Enchanted Manor",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:04",
    "previewVideo": "/media/projects/project-2026-08-31-27-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-27-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-27.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 35,
    "slug": "2-2",
    "templateSlug": "afterglow",
    "titleZh": "情人节",
    "titleEn": "Valentine's Day",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:13",
    "previewVideo": "/media/projects/2-2-preview.mp4",
    "fullVideo": "/media/projects/2-2-full.mp4",
    "cover": "/media/projects/photo/2-2.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 36,
    "slug": "project-2026-08-31-31",
    "templateSlug": "afterglow",
    "titleZh": "情人浴缸",
    "titleEn": "Lovers' Bathtub",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:05",
    "previewVideo": "/media/projects/project-2026-08-31-31-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-31-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-31.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 37,
    "slug": "project-2026-08-31-33",
    "templateSlug": "afterglow",
    "titleZh": "秋日宣言",
    "titleEn": "Autumn Manifesto",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:09",
    "previewVideo": "/media/projects/project-2026-08-31-33-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-33-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-33.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 38,
    "slug": "project-2026-08-31-35",
    "templateSlug": "afterglow",
    "titleZh": "神龙遗迹",
    "titleEn": "The Ruins of the Divine Dragon",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:13",
    "previewVideo": "/media/projects/project-2026-08-31-35-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-35-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-35.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 39,
    "slug": "2-3",
    "templateSlug": "afterglow",
    "titleZh": "圣诞八音盒",
    "titleEn": "Christmas Music Box",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:05",
    "previewVideo": "/media/projects/2-3-preview.mp4",
    "fullVideo": "/media/projects/2-3-full.mp4",
    "cover": "/media/projects/photo/2-3.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 40,
    "slug": "project-2026-08-31-39",
    "templateSlug": "afterglow",
    "titleZh": "圣诞乐园",
    "titleEn": "Christmas Wonderland",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:08",
    "previewVideo": "/media/projects/project-2026-08-31-39-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-39-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-39.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 41,
    "slug": "project-2026-08-31-41",
    "templateSlug": "afterglow",
    "titleZh": "天空之城",
    "titleEn": "Castle in the Sky",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:11",
    "previewVideo": "/media/projects/project-2026-08-31-41-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-41-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-41.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 42,
    "slug": "pv",
    "templateSlug": "afterglow",
    "titleZh": "星辰宝箱PV",
    "titleEn": "“Star Chest” PV",
    "categoryZh": "直播礼物",
    "categoryEn": "Live Stream Gifts",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "1:01",
    "previewVideo": "/media/projects/pv-preview.mp4",
    "fullVideo": "/media/projects/pv-full.mp4",
    "cover": "/media/projects/photo/pv.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 43,
    "slug": "project-2026-08-31-02",
    "templateSlug": "afterglow",
    "titleZh": "山海经x白桃饮料",
    "titleEn": "Classic of Mountains and Seas x White Peach Drink",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "0:37",
    "previewVideo": "/media/projects/project-2026-08-31-02-preview.mp4",
    "fullVideo": "/media/projects/project-2026-08-31-02-full.mp4",
    "cover": "/media/projects/photo/project-2026-08-31-02.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": true,
    "featuredOrder": 4,
    "enabled": true
  },
  {
    "order": 44,
    "slug": "ancient-time-travel-ghost-stories",
    "templateSlug": "afterglow",
    "titleZh": "古代穿越怪谈",
    "titleEn": "Ancient Time-Travel Ghost Stories",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "1:46",
    "previewVideo": "/media/projects/ancient-time-travel-ghost-stories-preview.mp4",
    "fullVideo": "/media/projects/ancient-time-travel-ghost-stories-full.mp4",
    "cover": "/media/projects/photo/ancient-time-travel-ghost-stories.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 45,
    "slug": "l-03-2",
    "templateSlug": "afterglow",
    "titleZh": "苏妩｜L-03 色欲睡衣_2",
    "titleEn": "苏妩｜L-03 色欲睡衣_2",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/l-03-2.webp",
    "cover": "/media/projects/photo/l-03-2.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 46,
    "slug": "w-04",
    "templateSlug": "afterglow",
    "titleZh": "周烈｜W-04 嗔欲",
    "titleEn": "周烈｜W-04 嗔欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/w-04.webp",
    "cover": "/media/projects/photo/w-04.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 47,
    "slug": "chatgpt-image-2026-8-13-09-29-20",
    "templateSlug": "afterglow",
    "titleZh": "ChatGPT_Image_2026年8月13日_09_29_20",
    "titleEn": "ChatGPT_Image_2026年8月13日_09_29_20",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/chatgpt-image-2026-8-13-09-29-20.webp",
    "cover": "/media/projects/photo/chatgpt-image-2026-8-13-09-29-20.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 48,
    "slug": "f2k-20260814142934-00001",
    "templateSlug": "afterglow",
    "titleZh": "F2K编辑-20260814142934_00001_",
    "titleEn": "F2K编辑-20260814142934_00001_",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/f2k-20260814142934-00001.webp",
    "cover": "/media/projects/photo/f2k-20260814142934-00001.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 49,
    "slug": "o-02",
    "templateSlug": "afterglow",
    "titleZh": "程未央｜O-02 痴欲",
    "titleEn": "程未央｜O-02 痴欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/o-02.webp",
    "cover": "/media/projects/photo/o-02.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 50,
    "slug": "project-2026-09-26-11",
    "templateSlug": "afterglow",
    "titleZh": "何小满_厨房_",
    "titleEn": "何小满_厨房_",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/project-2026-09-26-11.webp",
    "cover": "/media/projects/photo/project-2026-09-26-11.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 51,
    "slug": "a-07",
    "templateSlug": "afterglow",
    "titleZh": "何小满｜A-07 食欲",
    "titleEn": "何小满｜A-07 食欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/a-07.webp",
    "cover": "/media/projects/photo/a-07.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 52,
    "slug": "e-05",
    "templateSlug": "afterglow",
    "titleZh": "林见微｜E-05 妒欲",
    "titleEn": "林见微｜E-05 妒欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/e-05.webp",
    "cover": "/media/projects/photo/e-05.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 53,
    "slug": "g-01",
    "templateSlug": "afterglow",
    "titleZh": "陆钱生｜G-01 贪欲",
    "titleEn": "陆钱生｜G-01 贪欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/g-01.webp",
    "cover": "/media/projects/photo/g-01.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 54,
    "slug": "p-06",
    "templateSlug": "afterglow",
    "titleZh": "沈峥｜P-06 傲欲",
    "titleEn": "沈峥｜P-06 傲欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/p-06.webp",
    "cover": "/media/projects/photo/p-06.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 55,
    "slug": "p-06-2",
    "templateSlug": "afterglow",
    "titleZh": "沈峥｜P-06 健身服",
    "titleEn": "沈峥｜P-06 健身服",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/p-06-2.webp",
    "cover": "/media/projects/photo/p-06-2.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 56,
    "slug": "l-03",
    "templateSlug": "afterglow",
    "titleZh": "苏妩｜L-03 色欲",
    "titleEn": "苏妩｜L-03 色欲",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/l-03.webp",
    "cover": "/media/projects/photo/l-03.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 57,
    "slug": "l-03-3",
    "templateSlug": "afterglow",
    "titleZh": "苏妩｜L-03 色欲睡衣",
    "titleEn": "苏妩｜L-03 色欲睡衣",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "IMAGE",
    "previewVideo": "",
    "fullVideo": "/media/projects/photo/l-03-3.webp",
    "cover": "/media/projects/photo/l-03-3.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  },
  {
    "order": 58,
    "slug": "project-2026-09-26-14",
    "templateSlug": "afterglow",
    "titleZh": "山海宝典",
    "titleEn": "山海宝典",
    "categoryZh": "品牌短片",
    "categoryEn": "Brand Film",
    "year": "2026",
    "roleZh": "创意 / 导演 / 后期",
    "roleEn": "Creative / Direction / Post",
    "duration": "4:28",
    "previewVideo": "/media/projects/project-2026-09-26-14-preview.mp4",
    "fullVideo": "/media/projects/project-2026-09-26-14-full.mp4",
    "cover": "/media/projects/photo/project-2026-09-26-14.webp",
    "visual": "",
    "summaryZh": "",
    "summaryEn": "",
    "challengeZh": "",
    "challengeEn": "",
    "processZh": "",
    "processEn": "",
    "resultZh": "",
    "resultEn": "",
    "tools": [],
    "featured": false,
    "featuredOrder": null,
    "enabled": true
  }
] as const;
